### ISSUE TITLE
Github Pages'e geçirilmesi

### ISSUE THREAD

**Issue by ghost** [omergulcicek/reactjs#1]
Sistem github pages'e geçirilse daha iyi olmaz mı?

**Comment by omergulcicek** [comment]
İlk uygun vakitte gerekli çalışmaları yapacağım, teşekkür ederim ilgin için.

**Comment by BTaskaya** [comment]
+1

**Comment by omergulcicek** [comment]
Buradan önizlenebilir: https://omergulcicek.github.io/reactjs/

Dokümantasyonun şuan eksik yanları var, tamamlandığında linki readme'ye ekleyeceğim.

**Düzenleme**: Link anasayfaya eklendi ve sistem github pages'e taşındı. Tekrardan teşekkür ederim.
