### ISSUE TITLE
bind

### ISSUE THREAD

**Issue by nurikon** [omergulcicek/reactjs#12]
hocam anlatım süper olmuş ellerinize sağlık. çok istifade ettim. yalnız bind fonksiyonu için koyduğunuz link çalışmıyor. banada o lazımdı. güncellerseniz sevinirim.

**Comment by omergulcicek** [comment]
Teşekkür ederim. Bahsettiğin fonksiyon tam olarak hangi sayfada? @nurikon

**Comment by nurikon** [comment]
https://omergulcicek.github.io/react/hizli-baslangic/click-ve-change-olaylari
bu sayfada aşşağıdaki tırnak içinde olan kısım.
Bind etmek ile ilgili detaylı bilgi için kendi yazığım """"bind fonksiyonu"""" adlı makaleyi okuyabilirsiniz.

**Comment by omergulcicek** [comment]
Kişisel sitemi eskiden php ile geliştirmiştim, blogları kendi sitemde yayınlıyordum. Ama siteyi React ile geliştirip, makaleleri medium'da yazmaya başlayınca bahsettiğin linkteki makale göçmüş :/

Dokümanı da farklı bir link ile güncelliyorum, teşekkür ederim dikkatin için.

Şu makaleye bakabilirsin işini görecektir: [Call, Apply, Bind](https://turhancoskun.com/blog/javascript-ile-call-apply-ve-bind-kullanimi/)
