### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by MuhammetAdamoglu** [omergulcicek/reactjs#14]
Build alıp build dosyasını apache de çalıştırıyorum ancak tarayıcıda boş bir sayfa açılıyor. Nedeni nedir acaba?

**Comment by omergulcicek** [comment]
Neyden bahsettiğini anlamadım açıkçası, apache ile react kodu farklı dünyalar.

React kodlarını nodejs ile çalıştırabilirsin, kurulum kısmını okuyabilirsin:
https://omergulcicek.github.io/react/kurulum/reactjs-kurulumu
